name: Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_step.outputs.build_id }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Build and Test
        id: build_step
        run: |
          echo "Running build and tests"
          echo "build_id=$(date +%s)" >> $GITHUB_OUTPUT

  deploy-to-dev:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment: 
      name: development
      url: ${{ steps.deploy.outputs.deployment_url }}
    steps:
      - name: Deploy to Dev
        id: deploy
        run: echo "Deploying to dev environment"

  deploy-to-uat:
    needs: deploy-to-dev
    runs-on: ubuntu-latest
    environment:
      name: uat
      url: ${{ steps.deploy.outputs.deployment_url }}
    steps:
      - name: Run Integration Tests
        run: echo "Running integration tests"
      
      - name: Deploy to UAT
        id: deploy
        run: echo "Deploying to UAT environment"

  deploy-to-prod:
    needs: deploy-to-uat
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy.outputs.deployment_url }}
    steps:
      - name: Deploy to Production
        id: deploy
        run: echo "Deploying to production environment"
      
      - name: Smoke Tests
        run: echo "Running smoke tests"
      
      - name: Verify Monitoring
        run: echo "Verifying monitoring and alerts"